In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)      # jeśli chcesz widzieć wszystkie wiersze
pd.set_option("display.max_colwidth", None)  # nie ucina długich tekstów

# AI Open-Source Ecosystem on GitHub

## Pre-analysis

**Author:** xxxx

**Date:** August 2026

### Project Overview

This notebook focuses on preparing the collected GitHub repository data for exploratory data analysis (EDA). The primary objective is to validate the raw dataset, identify and resolve data quality issues, clean and standardize the data, engineer additional features, and produce a consistent dataset suitable for statistical analysis and visualization.

The cleaned dataset generated in this notebook serves as the input for the **GitHub Clean EDA** notebook, where the exploratory data analysis and research questions are addressed.

---

## Data Source

The dataset was collected using the GitHub REST Search API by querying 20 AI-related topics. Repository metadata was exported as a raw dataset and subsequently processed in this notebook.

---

## Project Objectives

The objectives of this notebook are to:

* validate the collected dataset,
* identify and remove duplicate repositories,
* detect and handle missing values,
* resolve inconsistencies introduced during data collection,
* standardize data types and feature values,
* remove non-informative features,
* engineer additional features required for analysis,
* produce a clean dataset for exploratory data analysis.

## 0. Technical review of raw data

In [3]:
raw_df = pd.read_csv('data/raw/github_ai_repositories.csv')
raw_df.head(1)

,id,node_id,name,full_name,private,html_url,description,fork,url,forks_url,keys_url,collaborators_url,teams_url,hooks_url,issue_events_url,events_url,assignees_url,branches_url,tags_url,blobs_url,git_tags_url,git_refs_url,trees_url,statuses_url,languages_url,stargazers_url,contributors_url,subscribers_url,subscription_url,commits_url,git_commits_url,comments_url,issue_comment_url,contents_url,compare_url,merges_url,archive_url,downloads_url,issues_url,pulls_url,milestones_url,notifications_url,labels_url,releases_url,deployments_url,created_at,updated_at,pushed_at,git_url,ssh_url,clone_url,svn_url,homepage,size,stargazers_count,watchers_count,language,has_issues,has_projects,has_downloads,has_wiki,has_pages,has_discussions,forks_count,mirror_url,archived,disabled,open_issues_count,allow_forking,is_template,web_commit_signoff_required,has_pull_requests,pull_request_creation_policy,topics,visibility,forks,open_issues,watchers,default_branch,score,owner.login,owner.id,owner.node_id,owner.avatar_url,owner.gravatar_id,owner.url,owner.html_url,owner.followers_url,owner.following_url,owner.gists_url,owner.starred_url,owner.subscriptions_url,owner.organizations_url,owner.repos_url,owner.events_url,owner.received_events_url,owner.type,owner.user_view_type,owner.site_admin,license.key,license.name,license.spdx_id,license.url,license.node_id,permissions.admin,permissions.maintain,permissions.push,permissions.triage,permissions.pull,license
0,614765452,R_kgDOJKSTjA,AutoGPT,Significant-Gravitas/AutoGPT,False,https://github.com/Significant-Gravitas/AutoGPT,"AutoGPT is the vision of accessible AI for everyone, to use and to build on. Our mission is to provide the tools, so that you can focus on what matters.",False,https://api.github.com/repos/Significant-Gravitas/AutoGPT,https://api.github.com/repos/Significant-Gravitas/AutoGPT/forks,https://api.github.com/repos/Significant-Gravitas/AutoGPT/keys{/key_id},https://api.github.com/repos/Significant-Gravitas/AutoGPT/collaborators{/collaborator},https://api.github.com/repos/Significant-Gravitas/AutoGPT/teams,https://api.github.com/repos/Significant-Gravitas/AutoGPT/hooks,https://api.github.com/repos/Significant-Gravitas/AutoGPT/issues/events{/number},https://api.github.com/repos/Significant-Gravitas/AutoGPT/events,https://api.github.com/repos/Significant-Gravitas/AutoGPT/assignees{/user},https://api.github.com/repos/Significant-Gravitas/AutoGPT/branches{/branch},https://api.github.com/repos/Significant-Gravitas/AutoGPT/tags,https://api.github.com/repos/Significant-Gravitas/AutoGPT/git/blobs{/sha},https://api.github.com/repos/Significant-Gravitas/AutoGPT/git/tags{/sha},https://api.github.com/repos/Significant-Gravitas/AutoGPT/git/refs{/sha},https://api.github.com/repos/Significant-Gravitas/AutoGPT/git/trees{/sha},https://api.github.com/repos/Significant-Gravitas/AutoGPT/statuses/{sha},https://api.github.com/repos/Significant-Gravitas/AutoGPT/languages,https://api.github.com/repos/Significant-Gravitas/AutoGPT/stargazers,https://api.github.com/repos/Significant-Gravitas/AutoGPT/contributors,https://api.github.com/repos/Significant-Gravitas/AutoGPT/subscribers,https://api.github.com/repos/Significant-Gravitas/AutoGPT/subscription,https://api.github.com/repos/Significant-Gravitas/AutoGPT/commits{/sha},https://api.github.com/repos/Significant-Gravitas/AutoGPT/git/commits{/sha},https://api.github.com/repos/Significant-Gravitas/AutoGPT/comments{/number},https://api.github.com/repos/Significant-Gravitas/AutoGPT/issues/comments{/number},https://api.github.com/repos/Significant-Gravitas/AutoGPT/contents/{+path},https://api.github.com/repos/Significant-Gravitas/AutoGPT/compare/{base}...{head},https://api.github.com/repos/Significant-Gravitas/AutoGPT/merges,https://api.github.com/repos/Significant-Gravitas/AutoGPT/{archive_format}{/ref},https://api.github.com/repos/Significant-Gravitas/AutoGPT/downloads,https://api.github.com/repos/Significant-Gravitas/AutoGPT/issues{/number},https://api.github.com/repos/Significant-Gravitas/AutoGPT/pulls{/number},https://api.github.com/repos/Significant-Gravitas/AutoGPT/milestones{/number},"https://api.github.com/repos/Significant-Gravitas/AutoGPT/notifications{?since,all,participating}",https://api.github.com/repos/Significant-Gravitas/AutoGPT/labels{/name},https://api.github.com/repos/Significant-Gravitas/AutoGPT/releases{/id},https://api.github.com/repos/Significant-Gravitas/AutoGPT/deployments,2023-03-16T09:21:07Z,2026-08-05T20:21:59Z,2026-08-05T20:28:48Z,git://github.com/Significant-Gravitas/AutoGPT.git,git@github.com:Significant-Gravitas/AutoGPT.git,https://github.com/Significant-Gravitas/AutoGPT.git,https://github.com/Significant-Gravitas/AutoGPT,https://agpt.co,638537,185832,185832,Python,True,True,False,True,False,False,46052,NaN,False,False,525,True,False,False,True,all,"['agentic-ai', 'agents', 'ai', 'artificial-intelligence', 'autonomous-agents', 'claude', 'gpt', 'llama-api', 'llm', 'openai', 'python']",public,46052,525,185832,master,1.0,Significant-Gravitas,130738209,O_kgDOB8roIQ,https://avatars.githubusercontent.com/u/130738209?v=4,NaN,https://api.github.com/users/Significant-Gravitas,https://github.com/Significant-Gravitas,https://api.github.com/users/Significant-Gravitas/followers,https://api.github.com/users/Significant-Gravitas/following{/other_user},https://api.github.com/users/Significant-Gravitas/gists{/gist_id},https://api.github.com/users/Significant-Gravitas/starred{/owner}{/repo},https://api.github.com/users/Significant-Gravitas/subscriptions,https://api.github.com/users/Significant-Gravitas/orgs,https://api.github.com/users/Significant-Gravitas/repos,https://api.github.com/users/Significant-Gravitas/events{/privacy},https://api.github.com/users/Significant-Gravitas/received_events,Organization,public,False,other,Other,NOASSERTION,NaN,MDc6TGljZW5zZTA=,False,False,False,False,True,NaN

In [4]:
# raw_df.drop_duplicates()

## 0.1 Remove url's cols

In [5]:
raw_df2 = raw_df.loc[:, ~raw_df.columns.str.contains("url", case=False)]
raw_df2.head(1)

,id,node_id,name,full_name,private,description,fork,created_at,updated_at,pushed_at,homepage,size,stargazers_count,watchers_count,language,has_issues,has_projects,has_downloads,has_wiki,has_pages,has_discussions,forks_count,archived,disabled,open_issues_count,allow_forking,is_template,web_commit_signoff_required,has_pull_requests,pull_request_creation_policy,topics,visibility,forks,open_issues,watchers,default_branch,score,owner.login,owner.id,owner.node_id,owner.gravatar_id,owner.type,owner.user_view_type,owner.site_admin,license.key,license.name,license.spdx_id,license.node_id,permissions.admin,permissions.maintain,permissions.push,permissions.triage,permissions.pull,license
0,614765452,R_kgDOJKSTjA,AutoGPT,Significant-Gravitas/AutoGPT,False,"AutoGPT is the vision of accessible AI for everyone, to use and to build on. Our mission is to provide the tools, so that you can focus on what matters.",False,2023-03-16T09:21:07Z,2026-08-05T20:21:59Z,2026-08-05T20:28:48Z,https://agpt.co,638537,185832,185832,Python,True,True,False,True,False,False,46052,False,False,525,True,False,False,True,all,"['agentic-ai', 'agents', 'ai', 'artificial-intelligence', 'autonomous-agents', 'claude', 'gpt', 'llama-api', 'llm', 'openai', 'python']",public,46052,525,185832,master,1.0,Significant-Gravitas,130738209,O_kgDOB8roIQ,NaN,Organization,public,False,other,Other,NOASSERTION,MDc6TGljZW5zZTA=,False,False,False,False,True,NaN

In [6]:
raw_df2.info(verbose=True, max_cols=None, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 54 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            20000 non-null  int64
 1   node_id                       20000 non-null  str
 2   name                          20000 non-null  str
 3   full_name                     20000 non-null  str
 4   private                       20000 non-null  bool
 5   description                   19926 non-null  str
 6   fork                          20000 non-null  bool
 7   created_at                    20000 non-null  str
 8   updated_at                    20000 non-null  str
 9   pushed_at                     20000 non-null  str
 10  homepage                      11757 non-null  str
 11  size                          20000 non-null  int64
 12  stargazers_count              20000 non-null  int64
 13  watchers_count                20000 non-null  int64
 14  language                      18078 non-null  str
 15  has_issues                    20000 non-null  bool
 16  has_projects                  20000 non-null  bool
 17  has_downloads                 20000 non-null  bool
 18  has_wiki                      20000 non-null  bool
 19  has_pages                     20000 non-null  bool
 20  has_discussions               20000 non-null  bool
 21  forks_count                   20000 non-null  int64
 22  archived                      20000 non-null  bool
 23  disabled                      20000 non-null  bool
 24  open_issues_count             20000 non-null  int64
 25  allow_forking                 20000 non-null  bool
 26  is_template                   20000 non-null  bool
 27  web_commit_signoff_required   20000 non-null  bool
 28  has_pull_requests             20000 non-null  bool
 29  pull_request_creation_policy  20000 non-null  str
 30  topics                        20000 non-null  str
 31  visibility                    20000 non-null  str
 32  forks                         20000 non-null  int64
 33  open_issues                   20000 non-null  int64
 34  watchers                      20000 non-null  int64
 35  default_branch                20000 non-null  str
 36  score                         20000 non-null  float64
 37  owner.login                   20000 non-null  str
 38  owner.id                      20000 non-null  int64
 39  owner.node_id                 20000 non-null  str
 40  owner.gravatar_id             0 non-null      float64
 41  owner.type                    20000 non-null  str
 42  owner.user_view_type          20000 non-null  str
 43  owner.site_admin              20000 non-null  bool
 44  license.key                   17039 non-null  str
 45  license.name                  17039 non-null  str
 46  license.spdx_id               17039 non-null  str
 47  license.node_id               17039 non-null  str
 48  permissions.admin             20000 non-null  bool
 49  permissions.maintain          20000 non-null  bool
 50  permissions.push              20000 non-null  bool
 51  permissions.triage            20000 non-null  bool
 52  permissions.pull              20000 non-null  bool
 53  license                       0 non-null      float64
dtypes: bool(20), float64(3), int64(10), str(21)
memory usage: 5.6 MB

## 0.2 Preserving selected columns for analysis

In [7]:
columns_to_keep = [
    "id",
    "name",
    "full_name",
    "description",
    "created_at",
    "updated_at",
    "pushed_at",
    "homepage",
    "size",
    "stargazers_count",
    "forks_count",
    "open_issues_count",
    "language",
    "topics",
    "owner.login",
    "owner.type",
    "license.name",
    "license.spdx_id",
    "fork",
    "archived",
    "has_issues",
    "has_wiki",
    "has_pages",
    "has_discussions",
]

df_cut = raw_df2[columns_to_keep].copy()

In [8]:
len(columns_to_keep)

24

In [9]:
df_cut.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 20000 non-null  int64
 1   name               20000 non-null  str
 2   full_name          20000 non-null  str
 3   description        19926 non-null  str
 4   created_at         20000 non-null  str
 5   updated_at         20000 non-null  str
 6   pushed_at          20000 non-null  str
 7   homepage           11757 non-null  str
 8   size               20000 non-null  int64
 9   stargazers_count   20000 non-null  int64
 10  forks_count        20000 non-null  int64
 11  open_issues_count  20000 non-null  int64
 12  language           18078 non-null  str
 13  topics             20000 non-null  str
 14  owner.login        20000 non-null  str
 15  owner.type         20000 non-null  str
 16  license.name       17039 non-null  str
 17  license.spdx_id    17039 non-null  str
 18  fork               20000 non-null  bool
 19  archived           20000 non-null  bool
 20  has_issues         20000 non-null  bool
 21  has_wiki           20000 non-null  bool
 22  has_pages          20000 non-null  bool
 23  has_discussions    20000 non-null  bool
dtypes: bool(6), int64(5), str(13)
memory usage: 2.9 MB

## 0.3 Removing duplicates

In [10]:
df_cut = df_cut.drop_duplicates()
# df_cut.head(1)

In [11]:
df_cut.duplicated().sum()

np.int64(0)

In [12]:
info_df = pd.DataFrame({
    'Column': df_cut.columns,
    "Duplicate rows": df_cut.duplicated().sum(),
    "Duplicates": [df_cut[col].duplicated().sum() for col in df_cut.columns],
    'Non-null': df_cut.notnull().sum().values,
    'Missing values': df_cut.isna().sum().values,
    'Percentage of missing values': (df_cut.isna().sum() * 100 / df_cut.notnull().sum()).values,
    'Unique values': df_cut.nunique().values,
    'Data type': df_cut.dtypes.values,
})

# Display the table
info_df

,Column,Duplicate rows,Duplicates,Non-null,Missing values,Percentage of missing values,Unique values,Data type
0,id,0,93,13937,0,0.000000,13844,int64
1,name,0,454,13937,0,0.000000,13483,str
2,full_name,0,93,13937,0,0.000000,13844,str
3,description,0,170,13876,61,0.439608,13766,str
4,created_at,0,93,13937,0,0.000000,13844,str
5,updated_at,0,456,13937,0,0.000000,13481,str
6,pushed_at,0,106,13937,0,0.000000,13831,str
7,homepage,0,6448,7814,6123,78.359355,7488,str
8,size,0,3276,13937,0,0.000000,10661,int64
9,stargazers_count,0,9257,13937,0,0.000000,4680,int64
10,forks_count,0,12002,13937,0,0.000000,1935,int64
11,open_issues_count,0,13288,13937,0,0.000000,649,int64
12,language,0,13846,12695,1242,9.783379,90,str
13,topics,0,219,13937,0,0.000000,13718,str
14,owner.login,0,3695,13937,0,0.000000,10242,str
15,owner.type,0,13935,13937,0,0.000000,2,str
16,license.name,0,13905,11738,2199,18.734026,31,str
17,license.spdx_id,0,13905,11738,2199,18.734026,31,str
18,fork,0,13936,13937,0,0.000000,1,bool
19,archived,0,13935,13937,0,0.000000,2,bool
20,has_issues,0,13935,13937,0,0.000000,2,bool
21,has_wiki,0,13935,13937,0,0.000000,2,bool
22,has_pages,0,13935,13937,0,0.000000,2,bool
23,has_discussions,0,13935,13937,0,0.000000,2,bool

In [13]:
df_cut[df_cut["id"].duplicated(keep=False)].sort_values("id").head(2)

,id,name,full_name,description,created_at,updated_at,pushed_at,homepage,size,stargazers_count,forks_count,open_issues_count,language,topics,owner.login,owner.type,license.name,license.spdx_id,fork,archived,has_issues,has_wiki,has_pages,has_discussions
3005,5108051,opencv,opencv/opencv,Open Source Computer Vision Library,2012-07-19T09:40:17Z,2026-08-05T19:51:05Z,2026-08-05T12:36:48Z,https://opencv.org,564658,90309,56954,2774,C++,"['c-plus-plus', 'computer-vision', 'deep-learning', 'image-processing', 'opencv']",opencv,Organization,Apache License 2.0,Apache-2.0,False,False,True,True,False,True
16000,5108051,opencv,opencv/opencv,Open Source Computer Vision Library,2012-07-19T09:40:17Z,2026-08-05T19:51:05Z,2026-08-05T12:36:48Z,https://opencv.org,564658,90309,56955,2774,C++,"['c-plus-plus', 'computer-vision', 'deep-learning', 'image-processing', 'opencv']",opencv,Organization,Apache License 2.0,Apache-2.0,False,False,True,True,False,True

## 0.3.1 Remove records with identical "id"

In [14]:
df_cut = df_cut.drop_duplicates(subset="id").reset_index(drop=True)

In [15]:
df_cut["id"].duplicated().sum()

np.int64(0)

In [16]:
info_df

,Column,Duplicate rows,Duplicates,Non-null,Missing values,Percentage of missing values,Unique values,Data type
0,id,0,93,13937,0,0.000000,13844,int64
1,name,0,454,13937,0,0.000000,13483,str
2,full_name,0,93,13937,0,0.000000,13844,str
3,description,0,170,13876,61,0.439608,13766,str
4,created_at,0,93,13937,0,0.000000,13844,str
5,updated_at,0,456,13937,0,0.000000,13481,str
6,pushed_at,0,106,13937,0,0.000000,13831,str
7,homepage,0,6448,7814,6123,78.359355,7488,str
8,size,0,3276,13937,0,0.000000,10661,int64
9,stargazers_count,0,9257,13937,0,0.000000,4680,int64
10,forks_count,0,12002,13937,0,0.000000,1935,int64
11,open_issues_count,0,13288,13937,0,0.000000,649,int64
12,language,0,13846,12695,1242,9.783379,90,str
13,topics,0,219,13937,0,0.000000,13718,str
14,owner.login,0,3695,13937,0,0.000000,10242,str
15,owner.type,0,13935,13937,0,0.000000,2,str
16,license.name,0,13905,11738,2199,18.734026,31,str
17,license.spdx_id,0,13905,11738,2199,18.734026,31,str
18,fork,0,13936,13937,0,0.000000,1,bool
19,archived,0,13935,13937,0,0.000000,2,bool
20,has_issues,0,13935,13937,0,0.000000,2,bool
21,has_wiki,0,13935,13937,0,0.000000,2,bool
22,has_pages,0,13935,13937,0,0.000000,2,bool
23,has_discussions,0,13935,13937,0,0.000000,2,bool

## 0.4 Remove Missing values

In [17]:
df_cut["description"] = df_cut["description"].fillna("No description")
df_cut["homepage"] = df_cut["homepage"].fillna("No homepage")
df_cut["language"] = df_cut["language"].fillna("Unknown")
df_cut["license.name"] = df_cut["license.name"].fillna("No license")
df_cut["license.spdx_id"] = df_cut["license.spdx_id"].fillna("No license id")

In [18]:
len(df_cut)

13844

In [19]:
df_cut.describe()

,id,size,stargazers_count,forks_count,open_issues_count
count,1.384400e+04,1.384400e+04,13844.000000,13844.000000,13844.000000
mean,6.432911e+08,9.056828e+04,3061.527015,481.573028,56.177116
std,3.920407e+08,6.842057e+05,10745.410809,2175.410338,361.114443
min,1.120850e+05,0.000000e+00,3.000000,0.000000,0.000000
25%,2.413655e+08,1.420000e+03,214.000000,27.000000,2.000000
50%,6.607836e+08,9.814000e+03,602.000000,90.000000,8.000000
75%,9.841386e+08,5.177000e+04,2013.000000,286.250000,31.000000
max,1.322792e+09,5.593504e+07,385254.000000,80984.000000,28301.000000

In [20]:
print(len(df_cut))

df_cut = df_cut.drop_duplicates(subset="id")

print(len(df_cut))

13844
13844

In [21]:
df_cut["created_at"] = pd.to_datetime(df_cut["created_at"])

print(df_cut["created_at"].min())
print(df_cut["created_at"].max())

2009-01-21 21:02:59+00:00
2026-08-04 10:01:35+00:00

In [22]:
df_cut["created_year"] = df_cut["created_at"].dt.year

df_cut["created_year"].value_counts().sort_index()

created_year
2009       5
2010       6
2011      23
2012      29
2013      39
2014      84
2015     136
2016     409
2017     855
2018     916
2019     866
2020     843
2021     626
2022     775
2023    2215
2024    1670
2025    2239
2026    2108
Name: count, dtype: int64

In [23]:
df_cut["stargazers_count"].describe()

count     13844.000000
mean       3061.527015
std       10745.410809
min           3.000000
25%         214.000000
50%         602.000000
75%        2013.000000
max      385254.000000
Name: stargazers_count, dtype: float64

In [24]:
df_cut.info()

<class 'pandas.DataFrame'>
RangeIndex: 13844 entries, 0 to 13843
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 13844 non-null  int64
 1   name               13844 non-null  str
 2   full_name          13844 non-null  str
 3   description        13844 non-null  str
 4   created_at         13844 non-null  datetime64[us, UTC]
 5   updated_at         13844 non-null  str
 6   pushed_at          13844 non-null  str
 7   homepage           13844 non-null  str
 8   size               13844 non-null  int64
 9   stargazers_count   13844 non-null  int64
 10  forks_count        13844 non-null  int64
 11  open_issues_count  13844 non-null  int64
 12  language           13844 non-null  str
 13  topics             13844 non-null  str
 14  owner.login        13844 non-null  str
 15  owner.type         13844 non-null  str
 16  license.name       13844 non-null  str
 17  license.spdx_id    13844 non-null  str
 18  fork               13844 non-null  bool
 19  archived           13844 non-null  bool
 20  has_issues         13844 non-null  bool
 21  has_wiki           13844 non-null  bool
 22  has_pages          13844 non-null  bool
 23  has_discussions    13844 non-null  bool
 24  created_year       13844 non-null  int32
dtypes: bool(6), datetime64[us, UTC](1), int32(1), int64(5), str(12)
memory usage: 2.0 MB

In [25]:
# df_cut['language'].isna().sum().sum()
df_cut['language'].unique()
df_cut["language"].value_counts(normalize=True) * 100

language
Python               48.620341
TypeScript           11.398440
Unknown               8.956949
Jupyter Notebook      8.422421
JavaScript            3.943947
Go                    3.033805
Rust                  2.650968
C++                   2.585958
Java                  1.581913
HTML                  1.538573
Shell                 1.054608
C#                    0.881248
Swift                 0.678995
Kotlin                0.447847
C                     0.426177
PHP                   0.404507
Vue                   0.390061
TeX                   0.274487
Lua                   0.245594
Ruby                  0.187807
MDX                   0.180584
Dart                  0.173360
CSS                   0.166137
Julia                 0.130020
Scala                 0.101127
Cuda                  0.093903
R                     0.093903
MATLAB                0.086680
PowerShell            0.086680
Svelte                0.086680
Emacs Lisp            0.079457
Zig                   0.065010
Elixir                0.065010
Markdown              0.057787
Astro                 0.050563
Clojure               0.050563
GDScript              0.043340
Makefile              0.043340
Pascal                0.043340
AutoHotkey            0.021670
Dockerfile            0.021670
Solidity              0.021670
Objective-C           0.021670
HCL                   0.021670
SCSS                  0.021670
Bicep                 0.021670
Nim                   0.014447
VHDL                  0.014447
CMake                 0.014447
Lean                  0.014447
YARA                  0.014447
Vim Script            0.014447
Jsonnet               0.014447
EJS                   0.014447
Apex                  0.014447
1C Enterprise         0.014447
Macaulay2             0.014447
Perl                  0.014447
Prolog                0.014447
Matlab                0.014447
Tcl                   0.007223
ReScript              0.007223
OCaml                 0.007223
Nunjucks              0.007223
PureBasic             0.007223
Mojo                  0.007223
PLpgSQL               0.007223
Awk                   0.007223
LLVM                  0.007223
Jinja                 0.007223
Nix                   0.007223
Starlark              0.007223
JSON                  0.007223
APL                   0.007223
MoonScript            0.007223
Stata                 0.007223
TypeSpec              0.007223
Move                  0.007223
Open Policy Agent     0.007223
Blade                 0.007223
MoonBit               0.007223
Haskell               0.007223
Elm                   0.007223
Roff                  0.007223
Visual Basic 6.0      0.007223
NASL                  0.007223
Modelica              0.007223
Objective-C++         0.007223
Verilog               0.007223
NewLisp               0.007223
MLIR                  0.007223
Name: proportion, dtype: float64

In [26]:
# no_lang = df_cut[df_cut["language"].isna()]
# no_lang.sample()

#### Repositories with missing values in the language column were excluded, as they primarily represented documentation, paper lists, and other non-code resources that were outside the scope of this analysis.

In [27]:
df_cut = df_cut[df_cut["language"].notna()].copy()
df_cut.info()

<class 'pandas.DataFrame'>
RangeIndex: 13844 entries, 0 to 13843
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 13844 non-null  int64
 1   name               13844 non-null  str
 2   full_name          13844 non-null  str
 3   description        13844 non-null  str
 4   created_at         13844 non-null  datetime64[us, UTC]
 5   updated_at         13844 non-null  str
 6   pushed_at          13844 non-null  str
 7   homepage           13844 non-null  str
 8   size               13844 non-null  int64
 9   stargazers_count   13844 non-null  int64
 10  forks_count        13844 non-null  int64
 11  open_issues_count  13844 non-null  int64
 12  language           13844 non-null  str
 13  topics             13844 non-null  str
 14  owner.login        13844 non-null  str
 15  owner.type         13844 non-null  str
 16  license.name       13844 non-null  str
 17  license.spdx_id    13844 non-null  str
 18  fork               13844 non-null  bool
 19  archived           13844 non-null  bool
 20  has_issues         13844 non-null  bool
 21  has_wiki           13844 non-null  bool
 22  has_pages          13844 non-null  bool
 23  has_discussions    13844 non-null  bool
 24  created_year       13844 non-null  int32
dtypes: bool(6), datetime64[us, UTC](1), int32(1), int64(5), str(12)
memory usage: 2.0 MB


## 0.5 Fixing missing values

In [28]:
df_cut["description"] = df_cut["description"].fillna("No description")
df_cut["homepage"] = df_cut["homepage"].fillna("No homepage")
df_cut["language"] = df_cut["language"].fillna("Unknown")
df_cut["license.name"] = df_cut["license.name"].fillna("No license")
df_cut["license.spdx_id"] = df_cut["license.spdx_id"].fillna("No license")

In [29]:
info_df = pd.DataFrame({
    'Column': df_cut.columns,
    "Duplicate rows": df_cut.duplicated().sum(),
    "Duplicates": [df_cut[col].duplicated().sum() for col in df_cut.columns],
    'Non-null': df_cut.notnull().sum().values,
    'Missing values': df_cut.isna().sum().values,
    'Percentage of missing values': (df_cut.isna().sum() * 100 / df_cut.notnull().sum()).values,
    'Unique values': df_cut.nunique().values,
    'Data type': df_cut.dtypes.values,
})

# Display the table
info_df

,Column,Duplicate rows,Duplicates,Non-null,Missing values,Percentage of missing values,Unique values,Data type
0,id,0,0,13844,0,0.0,13844,int64
1,name,0,361,13844,0,0.0,13483,str
2,full_name,0,0,13844,0,0.0,13844,str
3,description,0,77,13844,0,0.0,13767,str
4,created_at,0,0,13844,0,0.0,13844,"datetime64[us, UTC]"
5,updated_at,0,399,13844,0,0.0,13445,str
6,pushed_at,0,40,13844,0,0.0,13804,str
7,homepage,0,6355,13844,0,0.0,7489,str
8,size,0,3191,13844,0,0.0,10653,int64
9,stargazers_count,0,9191,13844,0,0.0,4653,int64
10,forks_count,0,11920,13844,0,0.0,1924,int64
11,open_issues_count,0,13202,13844,0,0.0,642,int64
12,language,0,13753,13844,0,0.0,91,str
13,topics,0,126,13844,0,0.0,13718,str
14,owner.login,0,3602,13844,0,0.0,10242,str
15,owner.type,0,13842,13844,0,0.0,2,str
16,license.name,0,13812,13844,0,0.0,32,str
17,license.spdx_id,0,13812,13844,0,0.0,32,str
18,fork,0,13843,13844,0,0.0,1,bool
19,archived,0,13842,13844,0,0.0,2,bool
20,has_issues,0,13842,13844,0,0.0,2,bool
21,has_wiki,0,13842,13844,0,0.0,2,bool
22,has_pages,0,13842,13844,0,0.0,2,bool
23,has_discussions,0,13842,13844,0,0.0,2,bool
24,created_year,0,13826,13844,0,0.0,18,int32

In [30]:
df_cut.info()

<class 'pandas.DataFrame'>
RangeIndex: 13844 entries, 0 to 13843
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 13844 non-null  int64
 1   name               13844 non-null  str
 2   full_name          13844 non-null  str
 3   description        13844 non-null  str
 4   created_at         13844 non-null  datetime64[us, UTC]
 5   updated_at         13844 non-null  str
 6   pushed_at          13844 non-null  str
 7   homepage           13844 non-null  str
 8   size               13844 non-null  int64
 9   stargazers_count   13844 non-null  int64
 10  forks_count        13844 non-null  int64
 11  open_issues_count  13844 non-null  int64
 12  language           13844 non-null  str
 13  topics             13844 non-null  str
 14  owner.login        13844 non-null  str
 15  owner.type         13844 non-null  str
 16  license.name       13844 non-null  str
 17  license.spdx_id    13844 non-null  str
 18  fork               13844 non-null  bool
 19  archived           13844 non-null  bool
 20  has_issues         13844 non-null  bool
 21  has_wiki           13844 non-null  bool
 22  has_pages          13844 non-null  bool
 23  has_discussions    13844 non-null  bool
 24  created_year       13844 non-null  int32
dtypes: bool(6), datetime64[us, UTC](1), int32(1), int64(5), str(12)
memory usage: 2.0 MB

## 0.6 Remove colum fork

In [31]:
df_cut.drop(columns="fork", inplace=True)

In [ ]:
df_cut = df_cut.reset_index(drop=True)
df_cut.to_csv("data/processed/github_ai_repositories_clean.csv", index=False)